spring:
  application:
    name: service_a

  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: manual
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: service-a
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    openfeign:
      client:
        config:
          messageClient:
            url: ${SERVICE_B_URL}
